### ISSUE TITLE
Adding Angular App calling Web API B2C

### ISSUE THREAD

**Issue by KanishkaB** [PramodKumarHK89/IdAceCodeEditor#1]
Adding Angular App calling Web API B2C
[Config.zip](https://github.com/PramodKumarHK89/IdAceCodeEditor/files/9278913/Config.zip)

**Comment by PramodKumarHK89** [comment]
@KanishkaB : B2C is not yet supported in the tool. Additionally, you can check in the config file and push a PR instead of adding it
